export const OBJEKTUMLISTA = [
    {kep:"kepek/kep1.jpg", id: 0},
    {kep:"kepek/kep2.jpg", id: 1},
    {kep:"kepek/kep3.jpg", id: 2},
    {kep:"kepek/kep4.jpg", id: 3},
    {kep:"kepek/kep5.jpg", id: 4},
    {kep:"kepek/kep6.jpg", id: 5},
    {kep:"kepek/kep7.jpg", id: 6},
    {kep:"kepek/kep8.jpg", id: 7},
    {kep:"kepek/kep9.jpg", id: 8},
    {kep:"kepek/kep10.jpg", id: 9},
    {kep:"kepek/kep11.jpg", id: 10},
    {kep:"kepek/kep12.jpg", id: 11},
    {kep:"kepek/kep13.jpg", id: 12},
    {kep:"kepek/kep14.jpg", id: 13},
    {kep:"kepek/kep15.jpg", id: 14},
    {kep:"kepek/kep16.jpg", id: 15},
    {kep:"kepek/kep17.jpg", id: 16},
    {kep:"kepek/kep18.jpg", id: 17},
    {kep:"kepek/kep19.jpg", id: 18},
    {kep:"kepek/kep20.jpg", id: 19}
]